name: send-a-joke
on:
  schedule:
    - cron:  '0 14 * * FRI'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Send it, yo 
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: ./send-joke.sh
      - name: Keep repo active with empty commit
        if: ${{ github.event_name == 'schedule' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keep send-a-joke workflow active"
          git push
