name: workflow-keep-alive
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@1.0.10

